server:
  port: 8080
spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: user

logging:
  level:
   root: info
   org.springframework.data: info
   org.springframework.data.mongodb.core.MongoTemplate: info